# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4746d9876364b7147930b9f59719959c5917f17c0dfb34e7adeb573d827376368866b44415a2c0402b80c744a6db7d2797729abe1fa450899b67dd1e1511f00

test:
  secret_key_base: 0b19f1d36866de985c72c3790f929c9d6f5f74ff6aedb0256161425bc7e1a1e29d8f18406d4ec3c8cbcc87e72ba666cecbc77e0abaf6b7be835e600da29de67f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
